services:
  ingestion-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestion-api
    ports:
      - "5198:5198"
    environment:
      # Força o Kestrel a rodar na porta 5198 dentro do container
      - ASPNETCORE_URLS=http://+:5198 
      - ASPNETCORE_ENVIRONMENT=Development
      
      # --- Credenciais AWS (Injetadas do ambiente host) ---

      - AWS_ACCESS_KEY_ID= "${AWS_ACCESS_KEY_ID}" 
      - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
      # --- Configurações AWS (Mapeamento do appsettings "AWS") ---
      - AWS__Region=sa-east-1
      - AWS__SnsTopicArn=arn:aws:sns:sa-east-1:316295889438:agrosolutions-raw-data
      
    networks:
      - agrosolutions-network

networks:
  agrosolutions-network:
    external: true