apiVersion: v1
kind: Secret
metadata:
  name: ingestion-aws-secrets
  namespace: agrosolutions
type: Opaque
data:
  # Coloque aqui o resultado do comando base64 das suas chaves
  # Exemplo: echo -n "SUA_CHAVE" | base64
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_B64}"       
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_B64}"  # Substitua pelo seu Base64