apiVersion: v1
kind: Service
metadata:
  name: service-ingestion
  namespace: agrosolutions
spec:
  selector:
    app: service-ingestion
  ports:
    - protocol: TCP
      port: 80         # Porta externa do serviço (ClusterIP)
      targetPort: 8080 # Porta interna da aplicação (definida no Dockerfile)
  type: ClusterIP