// <auto-generated />
using System;
using AgrosolutionsServiceIngestion.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgrosolutionsServiceIngestion.Infrastructure.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20260123213739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgrosolutionsServiceIngestion.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("talhao_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_type");

                    b.HasKey("Id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("AgrosolutionsServiceIngestion.Domain.Entities.Talhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.HasKey("Id");

                    b.ToTable("talhoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
